// <auto-generated />
using System;
using Health_Booking_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Health_Booking_MVC.Migrations
{
    [DbContext(typeof(HealthBookingDbContext))]
    [Migration("20260604124417_fixdb")]
    partial class fixdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Health_Booking_MVC.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 1,
                            ScheduleId = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Avatar = "anhbs3.jpg",
                            Description = "Chuyên khoa Tim Mạch",
                            ExperienceYears = 10,
                            FullName = "BS CKII. Ngô Trung Nam",
                            HospitalId = 1,
                            Phone = "0901 234 501",
                            SpecializationId = 6,
                            UserId = 2
                        },
                        new
                        {
                            DoctorId = 2,
                            Avatar = "anhbs1.jpg",
                            Description = "Chuyên khoa Tim mạch",
                            ExperienceYears = 5,
                            FullName = "BS CKI. Nguyễn Thị Thanh Minh",
                            HospitalId = 3,
                            Phone = "0901 234 502",
                            SpecializationId = 6,
                            UserId = 3
                        },
                        new
                        {
                            DoctorId = 3,
                            Avatar = "anhbs5.jpg",
                            Description = "Chuyên khoa Tai Mũi Họng",
                            ExperienceYears = 8,
                            FullName = "BS CKI. Nguyễn Phúc Thiện",
                            HospitalId = 2,
                            Phone = "0901 234 503",
                            SpecializationId = 9,
                            UserId = 4
                        },
                        new
                        {
                            DoctorId = 4,
                            Avatar = "anhbs6.jpg",
                            Description = "Chuyên khoa Sản - Phụ khoa",
                            ExperienceYears = 7,
                            FullName = "BS CKI. Đỗ Đăng Khoa",
                            HospitalId = 1,
                            Phone = "0901 234 504",
                            SpecializationId = 15,
                            UserId = 5
                        },
                        new
                        {
                            DoctorId = 5,
                            Avatar = "anhbs7.jpg",
                            Description = "Chuyên khoa Da liễu",
                            ExperienceYears = 10,
                            FullName = "ThS BS. Lê Vũ Tân",
                            HospitalId = 5,
                            Phone = "0901 234 505",
                            SpecializationId = 5,
                            UserId = 6
                        },
                        new
                        {
                            DoctorId = 6,
                            Avatar = "anhbs8.jpg",
                            Description = "Chuyên khoa Tai Mũi Họng",
                            ExperienceYears = 9,
                            FullName = "BS CKI. Bá Duy Khương",
                            HospitalId = 9,
                            Phone = "0901 234 506",
                            SpecializationId = 9,
                            UserId = 7
                        },
                        new
                        {
                            DoctorId = 7,
                            Avatar = "anhbs10.jpg",
                            Description = "Chuyên khoa Thần Kinh",
                            ExperienceYears = 12,
                            FullName = "PGS TS. Nguyễn Văn Hoà",
                            HospitalId = 6,
                            Phone = "0901 234 507",
                            SpecializationId = 7,
                            UserId = 8
                        },
                        new
                        {
                            DoctorId = 8,
                            Avatar = "anhbs9.jpg",
                            Description = "Chuyên khoa Da liễu",
                            ExperienceYears = 15,
                            FullName = "BS CKII. Lê Thị Lan",
                            HospitalId = 5,
                            Phone = "0901 234 508",
                            SpecializationId = 5,
                            UserId = 9
                        },
                        new
                        {
                            DoctorId = 9,
                            Avatar = "anhbs11.jpg",
                            Description = "Chuyên khoa Tim mạch",
                            ExperienceYears = 7,
                            FullName = "ThS BS. Nguyễn Hữu Phong",
                            HospitalId = 7,
                            Phone = "0901 234 509",
                            SpecializationId = 6,
                            UserId = 10
                        },
                        new
                        {
                            DoctorId = 10,
                            Avatar = "anhbs12.jpg",
                            Description = "Chuyên khoa Nội tiết niệu",
                            ExperienceYears = 20,
                            FullName = "BS CKI. Trần Đức Huy",
                            HospitalId = 3,
                            Phone = "0901 234 510",
                            SpecializationId = 13,
                            UserId = 11
                        },
                        new
                        {
                            DoctorId = 11,
                            Avatar = "anhbs13.jpg",
                            Description = "Chuyên khoa Ngoại cơ xương khớp",
                            ExperienceYears = 15,
                            FullName = "ThS BS. Đỗ Minh Quân",
                            HospitalId = 1,
                            Phone = "0901 234 511",
                            SpecializationId = 14,
                            UserId = 12
                        },
                        new
                        {
                            DoctorId = 12,
                            Avatar = "anhbs2.jpg",
                            Description = "Chuyên khoa Sản",
                            ExperienceYears = 10,
                            FullName = "BS CKII. Võ Ngọc Thanh",
                            HospitalId = 6,
                            Phone = "0901 234 512",
                            SpecializationId = 15,
                            UserId = 13
                        },
                        new
                        {
                            DoctorId = 13,
                            Avatar = "anhbs14.jpg",
                            Description = "Chuyên khoa Nội hô hấp",
                            ExperienceYears = 10,
                            FullName = "BS CKI. Nguyễn Tấn Phát",
                            HospitalId = 8,
                            Phone = "0901 234 513",
                            SpecializationId = 12,
                            UserId = 14
                        },
                        new
                        {
                            DoctorId = 14,
                            Avatar = "anhbs4.jpg",
                            Description = "Chuyên khoa Mắt",
                            ExperienceYears = 8,
                            FullName = "BS CKII. Trần Hồng Nhung",
                            HospitalId = 5,
                            Phone = "0901 234 514",
                            SpecializationId = 10,
                            UserId = 15
                        },
                        new
                        {
                            DoctorId = 15,
                            Avatar = "anhbs15.jpg",
                            Description = "Chuyên khoa Tai Mũi Họng",
                            ExperienceYears = 15,
                            FullName = "ThS BS. Phạm Minh Quân",
                            HospitalId = 6,
                            Phone = "0901 234 515",
                            SpecializationId = 9,
                            UserId = 16
                        },
                        new
                        {
                            DoctorId = 16,
                            Avatar = "anhbs2.jpg",
                            Description = "Chuyên khoa Da liễu",
                            ExperienceYears = 10,
                            FullName = "BS CKI. Võ Thị Ngọc",
                            HospitalId = 5,
                            Phone = "0901 234 516",
                            SpecializationId = 5,
                            UserId = 17
                        },
                        new
                        {
                            DoctorId = 17,
                            Avatar = "anhbs18.jpg",
                            Description = "Chuyên khoa Tim mạch",
                            ExperienceYears = 15,
                            FullName = "ThS BS. Nguyễn Hữu Dũng",
                            HospitalId = 6,
                            Phone = "0901 234 517",
                            SpecializationId = 6,
                            UserId = 18
                        },
                        new
                        {
                            DoctorId = 18,
                            Avatar = "anhbs1.jpg",
                            Description = "Chuyên khoa Nội tiêu hoá ",
                            ExperienceYears = 10,
                            FullName = "ThS BS. Trần Thị Thu Hằng",
                            HospitalId = 7,
                            Phone = "0901 234 518",
                            SpecializationId = 11,
                            UserId = 19
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CurrentPatients")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxPatients")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            CurrentPatients = 1,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            Address = "106 Nguyễn Huệ, Phường Quy Nhơn, Tỉnh Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "056 3820 289",
                            Image = "images/anhbenhvien/bvdk.jpg",
                            Name = "Bệnh viện đa khoa tỉnh Bình Định",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 2,
                            Address = "78 Trần Hưng Đạo, Quy Nhơn, Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0256 3893 247",
                            Image = "images/anhbenhvien/bvmat.jpg",
                            Name = "Bệnh viện Mắt Bình Định",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 3,
                            Address = "114 Trần Hưng Đạo, phường Quy Nhơn, tỉnh Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0269 6566 366",
                            Image = "images/anhbenhvien/bvquynhon.jpg",
                            Name = "Trung tâm Y tế Quy Nhơn",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 4,
                            Address = "Tổ 05, KV05, Phường Quy Nhơn Bắc, tỉnh Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0965 071 919",
                            Image = "images/anhbenhvien/yhoccotruyen.jpg",
                            Name = "Bệnh viện Y học cổ truyền & PHCN Bình Định",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 5,
                            Address = "05A Đường Chế Lan Viên, Quy Nhơn Nam, Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0256 3532 536",
                            Image = "images/anhbenhvien/bvquyhoa.jpg",
                            Name = "Bệnh viện Phong - Da liễu Trung ương Quy Hoà",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 6,
                            Address = "355 Trần Hưng Đạo, Phường Quy Nhơn, Gia Lai",
                            Description = "Bệnh viện tư",
                            Hotline = "0256 3822 900",
                            Image = "images/anhbenhvien/bvhoabinh.jpg",
                            Name = "Bệnh viện đa khoa Hoà Bình",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 7,
                            Address = "66 Đào Tấn, Xã Tuy Phước, Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0256 3833 315",
                            Image = "images/anhbenhvien/bvtuyphuoc.jpg",
                            Name = "Trung tâm Y tế huyện Tuy Phước",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 8,
                            Address = "54 An Dương Vương, Phường Quy Nhơn Nam, Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0256 3846 363",
                            Image = "images/anhbenhvien/quany13.jpg",
                            Name = "Bệnh viện Quân y 13",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 9,
                            Address = "420 Nguyễn Thái Học, Quy Nhơn Nam, Gia Lai",
                            Description = "Bệnh viện tư",
                            Hotline = "0256 3686 115",
                            Image = "images/anhbenhvien/dktp.jpg",
                            Name = "Bệnh viện đa khoa Thu Phúc",
                            Rating = 0
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Viêm họng cấp",
                            Prescription = "Paracetamol 500mg",
                            Symptoms = "Ho, sốt nhẹ",
                            Treatment = "Uống thuốc ấm"
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "Phường Quy Nhơn Bắc, Gia Lai",
                            DateOfBirth = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Thị B",
                            Gender = "Nữ",
                            Phone = "0911223344",
                            UserId = 20
                        },
                        new
                        {
                            PatientId = 2,
                            Address = "Phường Quy Nhơn Nam, Gia Lai",
                            DateOfBirth = new DateTime(1990, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn B",
                            Gender = "Nam",
                            Phone = "0911223345",
                            UserId = 21
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Name = "Bác sĩ gia đình"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Name = "Tiêu hoá gan mật"
                        },
                        new
                        {
                            SpecializationId = 3,
                            Name = "Nội tổng quát"
                        },
                        new
                        {
                            SpecializationId = 4,
                            Name = "Nội tiết"
                        },
                        new
                        {
                            SpecializationId = 5,
                            Name = "Da liễu"
                        },
                        new
                        {
                            SpecializationId = 6,
                            Name = "Nội tim mạch"
                        },
                        new
                        {
                            SpecializationId = 7,
                            Name = "Nội thần kinh"
                        },
                        new
                        {
                            SpecializationId = 8,
                            Name = "Nội cơ xương khớp"
                        },
                        new
                        {
                            SpecializationId = 9,
                            Name = "Tai mũi họng"
                        },
                        new
                        {
                            SpecializationId = 10,
                            Name = "Mắt"
                        },
                        new
                        {
                            SpecializationId = 11,
                            Name = "Nội tiêu hoá"
                        },
                        new
                        {
                            SpecializationId = 12,
                            Name = "Nội hô hấp"
                        },
                        new
                        {
                            SpecializationId = 13,
                            Name = "Nội tiết niệu"
                        },
                        new
                        {
                            SpecializationId = 14,
                            Name = "Ngoại cơ xương khớp"
                        },
                        new
                        {
                            SpecializationId = 15,
                            Name = "Sản - Phụ khoa"
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngotrungnam@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenthithanhminh@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenphucthien@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dodangkhoa@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "levutan@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "baduykhuong@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvanhoa@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lethilan@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenhuuphong@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranduchuy@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dominhquan@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vongocthanh@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyentanphat@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranhongnhung@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamminhquan@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuthingoc@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenhuudung@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranthithuhang@healthbooking.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patienta@gmail.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Patient"
                        },
                        new
                        {
                            UserId = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patientb@gmail.com",
                            Password = "$2a$11$.IaAh9ncKKq/7u608sBTKOIEUTv2hWuEy/AVXnLttucniyNC1rKtC",
                            Role = "Patient"
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Appointment", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.DoctorSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Doctor", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Health_Booking_MVC.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.DoctorSchedule", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.MedicalRecord", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Health_Booking_MVC.Models.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Patient", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Health_Booking_MVC.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Appointment", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Doctor", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.User", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
