// <auto-generated />
using System;
using Health_Booking_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Health_Booking_MVC.Migrations
{
    [DbContext(typeof(HealthBookingDbContext))]
    [Migration("20260602073921_updatedoctor")]
    partial class updatedoctor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Health_Booking_MVC.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 1,
                            ScheduleId = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Avatar = "anhbs1.jpg",
                            Description = "Chuyên khoa Tim Mạch",
                            ExperienceYears = 10,
                            FullName = "BS. Nguyễn Văn A",
                            HospitalId = 1,
                            Phone = "0901 234 567",
                            SpecializationId = 6,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CurrentPatients")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxPatients")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            CurrentPatients = 1,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            Address = "106 Nguyễn Huệ, Phường Quy Nhơn, Tỉnh Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "056 3820 289",
                            Image = "bvdk.jpg",
                            Name = "Bệnh viện đa khoa tỉnh Bình Định",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 2,
                            Address = "78 Trần Hưng Đạo, Quy Nhơn, Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0256 3893 247",
                            Image = "bvmat.jpg",
                            Name = "Bệnh viện Mắt Bình Định",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 3,
                            Address = "114 Trần Hưng Đạo, phường Quy Nhơn, tỉnh Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0269 6566 366",
                            Image = "bvquynhon.jpg",
                            Name = "Trung tâm Y tế Quy Nhơn",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 4,
                            Address = "Tổ 05, KV05, Phường Quy Nhơn Bắc, tỉnh Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0965 071 919",
                            Image = "yhoccotruyen.jpg",
                            Name = "Bệnh viện Y học cổ truyền & PHCN Bình Định",
                            Rating = 0
                        },
                        new
                        {
                            HospitalId = 5,
                            Address = "355 Trần Hưng Đạo, Phường Quy Nhơn, Gia Lai",
                            Description = "Bệnh viện công",
                            Hotline = "0256 3822 900",
                            Image = "bvhoabinh.jpg",
                            Name = "Bệnh viện đa khoa Hoà Bình",
                            Rating = 0
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Viêm họng cấp",
                            Prescription = "Paracetamol 500mg",
                            Symptoms = "Ho, sốt nhẹ",
                            Treatment = "Uống thuốc ấm"
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "Phường Quy Nhơn Bắc, Gia Lai",
                            DateOfBirth = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Thị B",
                            Gender = "Nữ",
                            Phone = "0911223344",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Name = "Bác sĩ gia đình"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Name = "Tiêu hoá gan mật"
                        },
                        new
                        {
                            SpecializationId = 3,
                            Name = "Nội tổng quát"
                        },
                        new
                        {
                            SpecializationId = 4,
                            Name = "Nội tiết"
                        },
                        new
                        {
                            SpecializationId = 5,
                            Name = "Da liễu"
                        },
                        new
                        {
                            SpecializationId = 6,
                            Name = "Nội tim mạch"
                        },
                        new
                        {
                            SpecializationId = 7,
                            Name = "Nội thần kinh"
                        },
                        new
                        {
                            SpecializationId = 8,
                            Name = "Nội cơ xương khớp"
                        },
                        new
                        {
                            SpecializationId = 9,
                            Name = "Tai mũi họng"
                        },
                        new
                        {
                            SpecializationId = 10,
                            Name = "Mắt"
                        },
                        new
                        {
                            SpecializationId = 11,
                            Name = "Nội tiêu hoá"
                        },
                        new
                        {
                            SpecializationId = 12,
                            Name = "Nội truyền nhiễm"
                        },
                        new
                        {
                            SpecializationId = 13,
                            Name = "Nội hô hấp"
                        },
                        new
                        {
                            SpecializationId = 14,
                            Name = "Nội tiết niệu"
                        },
                        new
                        {
                            SpecializationId = 15,
                            Name = "Khoa Nhi"
                        },
                        new
                        {
                            SpecializationId = 16,
                            Name = "Sản - Phụ khoa"
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@healthbooking.com",
                            Password = "AQAAAAIAAYagAAAAEJz9bWfS27vGxPhBToTfXmP5KzEwNk8d/V+Sg7XbVmxN6F1v==",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bacsitest@gmail.com",
                            Password = "AQAAAAIAAYagAAAAEOfkM98uXvPlFhGfT0YmX7Z8KwW1Nk6d/M9Xg8bVmxN5F2v==",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "benhnhantest@gmail.com",
                            Password = "AQAAAAIAAYagAAAAELmKP78uXvPlFhGfT0YmX7Z8KwW1Nk6d/M9Xg8bVmxN5F3v==",
                            Role = "Patient"
                        });
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Appointment", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.DoctorSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Doctor", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health_Booking_MVC.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Health_Booking_MVC.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.DoctorSchedule", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.MedicalRecord", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Health_Booking_MVC.Models.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Patient", b =>
                {
                    b.HasOne("Health_Booking_MVC.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Health_Booking_MVC.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Appointment", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Doctor", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Health_Booking_MVC.Models.User", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
